apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flink-platform-ui
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: flink-platform.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flink-platform-ui
                port:
                  number: 80
