apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-enrichment-sql
  namespace: tenant-10001
  labels:
    app.kubernetes.io/managed-by: flink-platform
data:
  statements.sql: |
    CREATE TABLE events (
      `event_id`   STRING,
      `user_id`    STRING,
      `session_id` STRING,
      `page`       STRING,
      `action`     STRING,
      `ts_ms`      BIGINT
    ) WITH (
      'connector'                  = 'kafka',
      'topic'                      = 'demo.events',
      'properties.bootstrap.servers' = 'kafka.ns-enterprise.svc.cluster.local:29092',
      'properties.group.id'        = 'demo-enrichment-group',
      'scan.startup.mode'          = 'earliest-offset',
      'format'                     = 'avro-confluent',
      'avro-confluent.url'         = 'http://schema-registry.ns-enterprise.svc.cluster.local:8081',
      'avro-confluent.subject'     = 'demo.events-value'
    );

    CREATE TABLE enriched_events (
      `event_id`       STRING,
      `user_id`        STRING,
      `session_id`     STRING,
      `page`           STRING,
      `action`         STRING,
      `ts_ms`          BIGINT,
      `enriched_event` STRING
    ) WITH (
      'connector'                  = 'kafka',
      'topic'                      = 'demo.enriched-events',
      'properties.bootstrap.servers' = 'kafka.ns-enterprise.svc.cluster.local:29092',
      'format'                     = 'avro-confluent',
      'avro-confluent.url'         = 'http://schema-registry.ns-enterprise.svc.cluster.local:8081',
      'avro-confluent.subject'     = 'demo.enriched-events-value',
      'sink.delivery-guarantee'    = 'at-least-once'
    );

    INSERT INTO enriched_events
    SELECT
      event_id,
      user_id,
      session_id,
      page,
      action,
      ts_ms,
      CONCAT(action, ' on ', page, ' by user ', user_id) AS enriched_event
    FROM events
